# Константы проекта

MAX_USER_EMAIL_LENGTH = 254
MAX_USER_PASSWORD_LENGTH = 150
MAX_USERNAME_LENGTH = 150
MAX_USER_FIRST_NAME_LENGTH = 150
MAX_USER_LAST_NAME_LENGTH = 150
MAX_USER_ROLE_LENGTH = 100
USER_ROLE = 'user'
ADMIN_ROLE = 'admin'
ROLES = ((USER_ROLE, 'Пользователь'), (ADMIN_ROLE, 'Администратор'))

MAX_TAG_NAME_LENGTH = 200
MAX_TAG_COLOR_LENGTH = 7
MAX_TAG_SLUG_LENGTH = 200

MAX_INGREDIENT_NAME_LENGTH = 200
MAX_INGREDIENT_MEASUREMENT_UNIT_LENGTH = 200
MIN_INGREDIENT_AMOUNT_VALUE = 1
MAX_INGREDIENT_AMOUNT_VALUE = 500

MAX_RECIPE_NAME_LENGTH = 200
MAX_RECIPE_TEXT_LENGTH = 3000

MIN_COOKING_TIME_VALUE = 1
MAX_COOKING_TIME_VALUE = 4320

FILTER_VALUE = [0, 1]
