# Константы проекта

MAX_USER_EMAIL_LENGHT = 254
MAX_USER_PASSWORD_LENGHT = 150
MAX_USERNAME_LENGHT = 150
MAX_USER_FIRST_NAME_LENGHT = 150
MAX_USER_LAST_NAME_LENGHT = 150
MAX_USER_ROLE_LENGHT = 100
USER_ROLE = 'user'
ADMIN_ROLE = 'admin'
ROLES = ((USER_ROLE, 'Пользователь'), (ADMIN_ROLE, 'Администратор'))

MAX_TAG_NAME_LENGHT = 200
MAX_TAG_COLOR_LENGHT = 7
MAX_TAG_SLUG_LENGHT = 200

MAX_INGREDIENT_NAME_LENGHT = 200
MAX_INGREDIENT_MEASUREMENT_UNIT_LENGHT = 200
MIN_INGREDIENT_AMOUNT_VALUE = 1
MAX_INGREDIENT_AMOUNT_VALUE = 20

MAX_RECIPE_NAME_LENGHT = 200
MAX_RECIPE_TEXT_LENGHT = 3000

MIN_COOKING_TIME_VALUE = 1
MAX_COOKING_TIME_VALUE = 4320
