# Generated by Django 3.2.16 on 2023-12-05 16:31

from django.db import migrations

import colorfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20231205_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None, verbose_name='Цвет'),
        ),
    ]
