# Generated by Django 3.2.16 on 2023-12-05 11:52

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow_author_isnt_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='author_isnt_user',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('author', django.db.models.expressions.F('user')), _negated=True), name='author_isnt_user'),
        ),
    ]
